// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "LottoGUI.h"

class NumbersTable : public Fl_Table
{
    int values[11][5];
public:
    NumbersTable(int x, int y, int w, int h, const char *l) : Fl_Table(x, y, w, h, l)
    {
        this->rows(11);
        this->cols(5);
    }
    ~NumbersTable() { }

protected:
    void draw_cell(TableContext context, int R=0,int C=0,int X=0,int Y=0, int W=0,int H=0) {
        switch (context)
        {
            case Fl_Table::CONTEXT_CELL:
                fl_draw_box(FL_THIN_UP_BOX, X,Y,W,H, FL_GRAY);
                fl_push_clip(X+3, Y+3, W-6, H-6);
                fl_color(FL_GREEN);
                fl_font(FL_COURIER, 12);
                if (0 == R)
                {
                    switch(C)
                    {
                        case 0:
                            fl_draw("12", X+3, Y+3, W-6, H-6, FL_ALIGN_CENTER);
                            break;
                        case 1:
                            fl_draw("13", X+3, Y+3, W-6, H-6, FL_ALIGN_CENTER);
                            break;
                        case 2:
                            fl_draw("14", X+3, Y+3, W-6, H-6, FL_ALIGN_CENTER);
                            break;
                        case 3:
                            fl_draw("15", X+3, Y+3, W-6, H-6, FL_ALIGN_CENTER);
                            break;
                        case 4:
                            fl_draw("22", X+3, Y+3, W-6, H-6, FL_ALIGN_CENTER);
                            break;
                    }
                }
                fl_pop_clip();
                break;
        }
        return;
    }
};


int main()
{
    auto* window = new Fl_Double_Window(900, 600);
    auto* table = new NumbersTable(25, 25, 850, 550, "Liczby MiniLotto");

    window->end();
    window->resizable(table);
    window->show();
    return(Fl::run());
}